### PR TITLE
14 schema registry

### PR DESCRIPTION
**Pull request by mukappalambda**
This PR made the following changes:
- Added the schema registry in `server/main.go`
- Wrote the `my-trader-cli` CLI with cobra
- Implemented the `schemas` and `send` commands for the `my-trader-cli` that allow users to
  - Generate a new schema
  - Apply the schema of interest
  - Send messages with a specified schema

Demonstrations are shown as follows:

1. Change directory to the project root directory.
2.  Run `make build`.
3. Start up the server.

```console
$ docker rm -f postgres
postgres
$ bash scripts/run.sh
5a183b59f9e8c1a2245261e124fe5051262bb2747f4c6fe7c146896d47802d94
Successfully copied 2.05kB to postgres:/var/lib/postgresql
CREATE TABLE
          List of relations
 Schema |   Name   | Type  |  Owner
--------+----------+-------+----------
 public | messages | table | postgres
(1 row)

$ export DATABASE_URL=postgresql://postgres:password@localhost:5432/demo?sslmode=disable
$ ./my-trader-server
...
```
Now the gRPC server and the schema registry service are running, at port 50051 and 8081, respectively.

4. Open up another terminal, run

```console
$ ./my-trader-cli help
Usage:
  my-trader-cli [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  schemas     Communicate with the schema registry service
  send

Flags:
      --config string   config file (default is $HOME/.client.yaml)
  -h, --help            help for my-trader-cli
  -t, --toggle          Help message for toggle

Use "my-trader-cli [command] --help" for more information about a command.
```

To generate a new schema template, run

```console
$ ./my-trader-cli schemas generate > example-schema.json
```

For demo purpose, edit the `example-schema.json` to the following contents:

```bash
{
  "subject": "finance",
  "name": "etf",
  "doc": "",
  "fields": [
    {
      "name": "trade",
      "type": "double",
      "doc": ""
    }
  ]
}
```

Once the `example-schema.json` is prepared, run:

```console
$ ./my-trader-cli schemas apply -f example-schema.json
{Id: Subject:finance Name:etf Doc: Fields:[{Name:trade Type:double Doc:}]}
{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}
```

The `apply` command will populate the given schema to the schema registry.

To retrieve the schema information, run

```console
## list all schemas
$ ./my-trader-cli schemas get
[{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}]
## list schemas with subject = "finance"
$ ./my-trader-cli schemas get --subject finance
[{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}]
## list the schema with name = "etf"
$ ./my-trader-cli schemas get --name etf
{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}
```

These commands are equivalent to the following operations:

```console
$ curl http://localhost:8081/schemas
[{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}]%
$ curl http://localhost:8081/schemas\?subject\=finance
[{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}]%
$ curl http://localhost:8081/schemas\?name\=etf
{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}%  
```

Finally, to send a message with a given schema, run

```console
$ ./my-trader-cli send -t my-topic -m '{"trade": 123.45}' --schema etf
Sent message: schema-subject=finance schema-name=etf trade=123.450000
```

Message fields which are inconsistent with the schema will be filtered out:

```console
$ ./my-trader-cli send -t my-topic -m '{"price": 123.45}' --schema etf
Sent message: schema-subject=finance schema-name=etf
$ ./my-trader-cli send -t my-topic -m '{"trade": 123.45, "date": "2024-06-01T12:34:56Z"}' --schema etf
Sent message: schema-subject=finance schema-name=etf trade=123.450000
```

The above detailed what's changed in this PR.

### CODE REVIEW

**Comment by joelan-v010** [comment]
```console
$ ./my-trader-cli schemas apply
failed to open "": open : no such file or directory
```
Maybe it's better to mark the `--filename` flag as required.

**Comment by joelan-v010** [comment]
> ```
> $ ./my-trader-cli schemas apply
> failed to open "": open : no such file or directory
> ```
> 
> Maybe it's better to mark the `--filename` flag as required.

```console
$ ./my-trader-cli schemas apply
Error: required flag(s) "filename" not set
Usage:
  my-trader-cli schemas apply [flags]

Aliases:
  apply, add

Flags:
  -f, --filename string              filename (required)
  -h, --help                         help for apply
      --schema-registry-url string   schema registry url (default "http://localhost:8081")

Global Flags:
      --config string   config file (default is $HOME/.client.yaml)

```

**Comment by mukappalambda** [comment]
this output seems to be a bit redundant:

```console
$ ./my-trader-cli schemas apply -f example-schema.json
{Id: Subject:finance Name:etf Doc: Fields:[{Name:trade Type:double Doc:}]}
{"id":"1","subject":"finance","name":"etf","doc":"","fields":[{"name":"trade","type":"double","doc":""}]}
```

Make it concise.

**Comment by mukappalambda** [comment]
Need to add examples for `my-trader-cli`:
- `./my-trader-cli schemas apply --help`
- `./my-trader-cli schemas check --help`
- `./my-trader-cli schemas get --help`
- `./my-trader-cli schemas send --help`

**Review by kevinliao852 — APPROVED** [review]
nit: Please consider using debug logs for debugging or refactoring in the future

**Pull request merged**
